
package obligatorio_dda.presentacion;

import componente.PanelRuleta;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import obligatorio_dda.dominio.Casillero;
import obligatorio_dda.dominio.Ficha;
import obligatorio_dda.dominio.Jugador;
import obligatorio_dda.dominio.Mesa;
import obligatorio_dda.dominio.TipoApuesta;
import obligatorio_dda.presentacion.controlador.JugarControlador;
import obligatorio_dda.presentacion.vista.JugarVista;

/**
 *
 * @author monte
 */
public class VentanaJugar extends javax.swing.JFrame implements JugarVista {


    private JugarControlador controlador;

    /**
     * Creates new form VentanaJugar
     */
    public VentanaJugar(Jugador jugador, Mesa mesa) {
        initComponents();
        this.controlador = new JugarControlador(this, mesa, jugador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_saldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_numRuleta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_numRonda = new javax.swing.JLabel();
        l_nomJugador = new javax.swing.JLabel();
        panelRuleta1 = new componente.PanelRuleta();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_estadisticas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_valorOcurrencia = new javax.swing.JTable();
        b_abandonar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        l_numSorteado = new javax.swing.JLabel();
        rb_cien = new javax.swing.JRadioButton();
        rb_cincuenta = new javax.swing.JRadioButton();
        rb_diez = new javax.swing.JRadioButton();
        rb_cinco = new javax.swing.JRadioButton();
        rb_uno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicacion Jugador");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Saldo $");

        l_saldo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_saldo.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Ruleta #");

        l_numRuleta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_numRuleta.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Ronda #");

        l_numRonda.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_numRonda.setText("0");

        l_nomJugador.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_nomJugador.setText("Nombre del Jugador");

        tbl_estadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ronda", "Total Apostado", "Ganado", "Perdido", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tbl_estadisticas);

        tbl_valorOcurrencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Valor", "Ocurrencia"
            }
        ));
        jScrollPane2.setViewportView(tbl_valorOcurrencia);

        b_abandonar.setText("Abandonar");
        b_abandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_abandonarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Numero sorteado:");

        l_numSorteado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_numSorteado.setText("0");

        rb_cien.setText("100");
        rb_cien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_cienItemStateChanged(evt);
            }
        });
        rb_cien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_cienStateChanged(evt);
            }
        });
        rb_cien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cienActionPerformed(evt);
            }
        });

        rb_cincuenta.setText("50");
        rb_cincuenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_cincuentaItemStateChanged(evt);
            }
        });
        rb_cincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cincuentaActionPerformed(evt);
            }
        });

        rb_diez.setText("10");
        rb_diez.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_diezItemStateChanged(evt);
            }
        });
        rb_diez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_diezActionPerformed(evt);
            }
        });

        rb_cinco.setText("5");
        rb_cinco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_cincoItemStateChanged(evt);
            }
        });
        rb_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cincoActionPerformed(evt);
            }
        });

        rb_uno.setText("1");
        rb_uno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_unoItemStateChanged(evt);
            }
        });
        rb_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_unoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(b_abandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(l_saldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(rb_uno)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_cinco)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_diez, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_cincuenta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(l_numRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb_cien)
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(l_numSorteado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(l_numRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(153, 153, 153)
                                        .addComponent(l_nomJugador)))))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_abandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_nomJugador)
                                    .addComponent(jLabel4)
                                    .addComponent(l_numRonda)
                                    .addComponent(jLabel2)
                                    .addComponent(l_numRuleta)
                                    .addComponent(jLabel1)
                                    .addComponent(l_saldo))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_numSorteado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_cincuenta)
                                    .addComponent(rb_cien)
                                    .addComponent(rb_diez)
                                    .addComponent(rb_cinco)
                                    .addComponent(rb_uno))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                        .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_cincuentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_cincuentaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            rb_cien.setSelected(false);
            rb_diez.setSelected(false);
            rb_cinco.setSelected(false);
            rb_uno.setSelected(false);
            panelRuleta1.eliminarEscuchadores();
        }
    }//GEN-LAST:event_rb_cincuentaItemStateChanged

    private void rb_cienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_cienItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            rb_cincuenta.setSelected(false);
            rb_diez.setSelected(false);
            rb_cinco.setSelected(false);
            rb_uno.setSelected(false);
            panelRuleta1.eliminarEscuchadores();
        }
    }//GEN-LAST:event_rb_cienItemStateChanged

    private void rb_cienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cienActionPerformed
        this.realizarApuesta(Ficha.Valor.CIEN.getValor(), rb_cien);
    }//GEN-LAST:event_rb_cienActionPerformed

    private void rb_cincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cincuentaActionPerformed
        this.realizarApuesta(Ficha.Valor.CINCUENTA.getValor(), rb_cincuenta);
    }//GEN-LAST:event_rb_cincuentaActionPerformed

    private void rb_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cincoActionPerformed
        this.realizarApuesta(Ficha.Valor.CINCO.getValor(), rb_cinco);
    }//GEN-LAST:event_rb_cincoActionPerformed

    private void rb_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_unoActionPerformed
        this.realizarApuesta(Ficha.Valor.UNO.getValor(), rb_uno);
    }//GEN-LAST:event_rb_unoActionPerformed

    private void rb_diezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_diezActionPerformed
        this.realizarApuesta(Ficha.Valor.DIEZ.getValor(), rb_diez);
    }//GEN-LAST:event_rb_diezActionPerformed


    private void rb_unoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_unoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            rb_cien.setSelected(false);
            rb_cincuenta.setSelected(false);
            rb_diez.setSelected(false);
            rb_cinco.setSelected(false);
            panelRuleta1.eliminarEscuchadores();
        }
    }//GEN-LAST:event_rb_unoItemStateChanged

    private void rb_cincoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_cincoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            rb_cien.setSelected(false);
            rb_cincuenta.setSelected(false);
            rb_diez.setSelected(false);
            rb_uno.setSelected(false);
            panelRuleta1.eliminarEscuchadores();
        }
    }//GEN-LAST:event_rb_cincoItemStateChanged

    private void rb_diezItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_diezItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            rb_cien.setSelected(false);
            rb_cincuenta.setSelected(false);
            rb_cinco.setSelected(false);
            rb_uno.setSelected(false);
            panelRuleta1.eliminarEscuchadores();
        }
    }//GEN-LAST:event_rb_diezItemStateChanged

    private void b_abandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_abandonarActionPerformed

        abandonarMesa();
    }//GEN-LAST:event_b_abandonarActionPerformed

    private void rb_cienStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_cienStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_cienStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_abandonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l_nomJugador;
    private javax.swing.JLabel l_numRonda;
    private javax.swing.JLabel l_numRuleta;
    private javax.swing.JLabel l_numSorteado;
    private javax.swing.JLabel l_saldo;
    private componente.PanelRuleta panelRuleta1;
    private javax.swing.JRadioButton rb_cien;
    private javax.swing.JRadioButton rb_cinco;
    private javax.swing.JRadioButton rb_cincuenta;
    private javax.swing.JRadioButton rb_diez;
    private javax.swing.JRadioButton rb_uno;
    private javax.swing.JTable tbl_estadisticas;
    private javax.swing.JTable tbl_valorOcurrencia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void activarTipoApuestasDeLaMesa(List<TipoApuesta> tipoApuestas) {
        // Desactiva todas las opciones primero
        for (int i = 0; i < 51; i++) {
            panelRuleta1.setVisible(i, false);
        }

        for (TipoApuesta t : tipoApuestas) {
            for (Casillero c : t.getCasilleros()) {
                panelRuleta1.setVisible(c.getUniversalCellCode(), true);

            }
        }

    }

    private void realizarApuesta(int valorDeFicha, JRadioButton radioButton) {

        if (radioButton.isSelected()) {
            panelRuleta1.agregar(new PanelRuleta.Escuchador() {
                @Override
                public void celdaSeleccionada(int universalCellCode) {

                    controlador.crearApuesta(universalCellCode, valorDeFicha);

                    if (controlador.ok) {
                        mostrarEnElPanel(universalCellCode, valorDeFicha);
                    }
                }
            });
        } else {
            panelRuleta1.eliminarEscuchadores();
        }
    }

    private void mostrarEnElPanel(int universalCellCode, int valorDeFicha) {
        int valorApuesta = panelRuleta1.getApuesta(universalCellCode) + valorDeFicha;
        panelRuleta1.setApuesta(universalCellCode, valorApuesta);
    }

    @Override
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private void abandonarMesa() {
        this.controlador.abandonarMesa();
    }

    @Override
    public void cerrar() {
        dispose();

    }

    @Override
    public void mostrarNumeroSorteado(String numeroSorteado) {
        l_numSorteado.setVisible(true);
        l_numSorteado.setText(numeroSorteado);
    }

    @Override
    public void nombreDelJugador(String nombre) {
        l_nomJugador.setText(nombre);

    }

    @Override
    public void numeroDeLaRonda(String numeroRonda) {
             l_numSorteado.setVisible(false);
        l_numRonda.setText(numeroRonda);
    }

    @Override
    public void numeroRuleta(String numeroRuleta) {
        l_numRuleta.setText(numeroRuleta);
    }

    @Override
    public void mostrarSaldoJugador(String saldo) {
        l_saldo.setText(saldo);
    }

    @Override
    public void bloquearPanel() {
        panelRuleta1.pausar();
        b_abandonar.setEnabled(false);
    }

    @Override
    public void activarPanel() {
        panelRuleta1.reanudar();
        panelRuleta1.limpiar();
        b_abandonar.setEnabled(true);
    }

}
