
package obligatorio_dda.presentacion;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;
import obligatorio_dda.dominio.Casillero;
import obligatorio_dda.dominio.Jugador;
import obligatorio_dda.dominio.Mesa;
import obligatorio_dda.dominio.Sesion;
import obligatorio_dda.dominio.TipoApuesta;
import obligatorio_dda.dominio.TipoEfecto;
import obligatorio_dda.presentacion.controlador.OperarControlador;
import obligatorio_dda.presentacion.vista.OperarVista;

/**
 *
 * @author monte
 */
public class VentanaOperar extends javax.swing.JFrame implements OperarVista {


    private OperarControlador controlador;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form VentanaOperarRuleta
     *
     * @param crupier
     */
    public VentanaOperar(Mesa mesa, Sesion sesion) {
        initComponents();

        this.controlador = new OperarControlador(this, mesa, sesion);

        b_cerrarMesa.setEnabled(false);
   
        list_jugadoresActivos.setCellRenderer(new JugadoresActivosRender());

        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Ronda");
        modeloTabla.addColumn("Balance anterior");
        modeloTabla.addColumn("Apuestas");
        modeloTabla.addColumn("Recoleccion");
        modeloTabla.addColumn("Liquidacion");
        modeloTabla.addColumn("Balance Posterior");
        tbl_balances.setModel(modeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRuleta1 = new componente.PanelRuleta();
        jLabel1 = new javax.swing.JLabel();
        l_cantidadApuestas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_totalApostado = new javax.swing.JLabel();
        cb_seleccionarEfecto = new javax.swing.JComboBox();
        b_lanzar = new javax.swing.JButton();
        l_ultimoNumSorteado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_balance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l_numRonda = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_numRuleta = new javax.swing.JLabel();
        b_cerrarMesa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_balances = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        l_ultimosLanzamientos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l_nombreCrupier = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_jugadoresActivos = new javax.swing.JList();
        b_pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicación Crupier - Operar ruleta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Apuestas:");

        l_cantidadApuestas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        l_cantidadApuestas.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("|");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Monto $");

        l_totalApostado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        l_totalApostado.setText("0");

        cb_seleccionarEfecto.setMinimumSize(new java.awt.Dimension(139, 30));
        cb_seleccionarEfecto.setPreferredSize(new java.awt.Dimension(139, 30));

        b_lanzar.setText("Lanzar");
        b_lanzar.setPreferredSize(new java.awt.Dimension(106, 30));
        b_lanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lanzarActionPerformed(evt);
            }
        });

        l_ultimoNumSorteado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_ultimoNumSorteado.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Balance $");

        l_balance.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_balance.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Ronda #");

        l_numRonda.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_numRonda.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Ruleta #");

        l_numRuleta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l_numRuleta.setText("0");

        b_cerrarMesa.setText("Cerrar mesa");
        b_cerrarMesa.setPreferredSize(new java.awt.Dimension(93, 30));
        b_cerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrarMesaActionPerformed(evt);
            }
        });

        jLabel5.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------");

        tbl_balances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_balances);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Últimos lanzamientos:");

        l_ultimosLanzamientos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_ultimosLanzamientos.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("CRUPIER");

        l_nombreCrupier.setText("jLabel10");

        jScrollPane3.setViewportView(list_jugadoresActivos);

        b_pagar.setText("Pagar");
        b_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(l_ultimosLanzamientos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelRuleta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(7, 7, 7)
                                        .addComponent(l_cantidadApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(l_totalApostado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(cb_seleccionarEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(b_lanzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addComponent(l_ultimoNumSorteado)))
                        .addContainerGap(242, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(l_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(l_numRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(l_numRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(l_nombreCrupier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(b_cerrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(l_nombreCrupier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cerrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l_balance)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addComponent(l_numRonda)
                            .addComponent(jLabel8)
                            .addComponent(l_numRuleta))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(l_cantidadApuestas)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(l_totalApostado)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_seleccionarEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_lanzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_ultimoNumSorteado)
                        .addComponent(b_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l_ultimosLanzamientos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrarMesaActionPerformed
        // TODO add your handling code here:
        cerrarMesa();
    }//GEN-LAST:event_b_cerrarMesaActionPerformed

    private void b_lanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lanzarActionPerformed
        lanzar();
    }//GEN-LAST:event_b_lanzarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cerrarMesa();
    }//GEN-LAST:event_formWindowClosed

    private void b_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pagarActionPerformed
        pagar();
    }//GEN-LAST:event_b_pagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cerrarMesa;
    private javax.swing.JButton b_lanzar;
    private javax.swing.JButton b_pagar;
    private javax.swing.JComboBox cb_seleccionarEfecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l_balance;
    private javax.swing.JLabel l_cantidadApuestas;
    private javax.swing.JLabel l_nombreCrupier;
    private javax.swing.JLabel l_numRonda;
    private javax.swing.JLabel l_numRuleta;
    private javax.swing.JLabel l_totalApostado;
    private javax.swing.JLabel l_ultimoNumSorteado;
    private javax.swing.JLabel l_ultimosLanzamientos;
    private javax.swing.JList list_jugadoresActivos;
    private componente.PanelRuleta panelRuleta1;
    private javax.swing.JTable tbl_balances;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarTipoEfectos(List<TipoEfecto> tipoEfectos) {
        for (TipoEfecto t : tipoEfectos) {
            cb_seleccionarEfecto.addItem(t);
        }

    }

    @Override
    public void agregarFila(String ronda, String balanceAnterior, String apuestas, String recoleccion, String balancePosterior) {
        // Agrega una fila al modelo de la tabla
        modeloTabla.addRow(new Object[]{ronda, balanceAnterior, apuestas, recoleccion, balancePosterior});
    }

    
    @Override
    public void mostrarApuestasDeLosJugadores(int universalCellCode, int valor) {

        panelRuleta1.setApuesta(universalCellCode, valor + panelRuleta1.getApuesta(universalCellCode));

    }

    private void cerrarMesa() {
        this.pagar();
        this.controlador.cerrarMesa();
    }

    @Override
    public void cerrar() {
        dispose();
    }

    private void lanzar() {
        TipoEfecto tipoEfecto = (TipoEfecto) cb_seleccionarEfecto.getSelectedItem();
        this.controlador.lanzar(tipoEfecto);
        b_cerrarMesa.setEnabled(true);
    }

    private void pagar() {
        this.controlador.pagar();
        b_cerrarMesa.setEnabled(false);
    }

    @Override
    public void mostrarNumeroSorteado(String numeroSorteado) {

        l_ultimoNumSorteado.setVisible(true);
        l_ultimoNumSorteado.setText(numeroSorteado);
    }

    @Override
    public void mostrarNumeroMesa(String numeroMesa) {
        l_numRuleta.setText(numeroMesa);
    }

    @Override
    public void mostrarNumeroRonda(String numeroRonda) {
        l_numRonda.setText(numeroRonda);
    }

    @Override
    public void activarTipoApuestasDeLaMesa(List<TipoApuesta> tipoApuestas) {
        // Desactiva todas las opciones primero
        for (int i = 0; i < 51; i++) {
            panelRuleta1.setVisible(i, false);
        }

        for (TipoApuesta t : tipoApuestas) {
            for (Casillero c : t.getCasilleros()) {
                panelRuleta1.setVisible(c.getUniversalCellCode(), true);

            }
        }
    }

    @Override
    public void mostrarJugadoresActivos(List<Jugador> jugadoresActivos) {
        list_jugadoresActivos.setListData(jugadoresActivos.toArray());
    }

    @Override
    public void mostrarCantidadyTotalApostado(String cantidadApuestas, String cantidadApostado) {
        l_cantidadApuestas.setText(cantidadApuestas);
        l_totalApostado.setText(cantidadApostado);
    }

    @Override
    public void limpiarPanel() {
        panelRuleta1.limpiar();
    }

    @Override
    public void mostrarBalance(String balance) {
        int b = Integer.parseInt(balance);
        if (b < 0) {

            l_balance.setText(balance);
            l_balance.setForeground(Color.red);
        } else {

            l_balance.setText(balance);
        }
    }

    @Override
    public void ocultarNumeroSorteado() {
        l_ultimoNumSorteado.setVisible(false);
    }

    @Override
    public void ultimosLanzamientos(List<Integer> ultimosLanzamientos) {
        StringBuilder texto = new StringBuilder();
        for (int n : ultimosLanzamientos) {
            texto.append(n).append(", ");
        }

        l_ultimosLanzamientos.setText(texto.toString().trim());
    }

    @Override
    public void mostrarNombreCrupier(String nombre) {
       l_nombreCrupier.setText(nombre);
    }

    private static class JugadoresActivosRender extends JLabel implements ListCellRenderer<Jugador> {

        @Override
        public Component getListCellRendererComponent(JList list, Jugador jugador, int index, boolean isSelected, boolean cellHasFocus) {
            this.setText("NOMBRE: " + jugador.getNombreCompleto() + " | SALDO: " + jugador.getSaldo());
            return this;
        }
    }
}
